game_modes = return {"nade_fight","classes","chaos","classic"}
barrier_area = return {pos2={z=140,x=140,y=129},pos1={z=0,x=0,y=0}}
teams = local _={};_[1]="flag_pos";_[2]="look_pos";_[3]="enabled";return {red={pos1={z=70,x=140,y=128.5},[_[1]]={z=130,x=76,y=33.5},[_[3]]=true,[_[2]]={z=-478,x=76,y=-32},pos2={z=140,x=0,y=-0.5}},blue={pos1={z=0,x=140,y=-0.5},[_[1]]={z=7,x=70,y=33.5},[_[3]]=true,[_[2]]={z=-601,x=70,y=-32},pos2={z=71,x=0,y=128.5}},yellow={pos1={z=140,x=140,y=-0.5},[_[1]]={z=78,x=132,y=37.5},[_[3]]=true,[_[2]]={z=-530,x=132,y=-28},pos2={z=0,x=70,y=128.5}},green={pos1={z=0,x=0,y=-0.5},[_[1]]={z=67,x=8,y=27.5},[_[3]]=true,[_[2]]={z=-541,x=8,y=-38},pos2={z=140,x=70,y=128.5}}}
chests = return {{pos1={z=126,x=72,y=28.5},pos2={z=131,x=80,y=28.5},amount=42},{pos1={z=74,x=128,y=32.5},pos2={z=82,x=133,y=32.5},amount=42},{pos1={z=6,x=66,y=28.5},pos2={z=11,x=74,y=28.5},amount=42},{pos1={z=63,x=7,y=22.5},pos2={z=71,x=12,y=22.5},amount=42}}
seasonal_end = 12.31
seasonal_start = 01.01
phys_jump = 1.3
phys_speed = 1
size = return {z=140,x=140,y=129}
map_version = 3
enabled = true
max_players = 32
name = Outer Space War
phys_gravity = 0.7
initial_stuff = return {"default:cobble 99","default:ladder_wood 99"}
author = DarkWizard
hint = 
license = CC-BY
others = You can never have too many asteroids
treasures = 
skybox = none
enable_shadows = 0.26
min_players = 1
start_time = 4500
time_speed = 0
