game_modes = return {"nade_fight","classes","potato","chaos","classic"}
barrier_area = return {pos1={z=0,x=0,y=0},pos2={z=140,x=140,y=129}}
teams = local _={};_[1]="enabled";_[2]="look_pos";_[3]="flag_pos";return {yellow={[_[2]]={y=-28,x=132,z=-530},[_[1]]=true,[_[3]]={z=78,x=132,y=37.5},pos1={z=140,x=140,y=-0.5},pos2={z=0,x=70,y=128.5}},red={[_[2]]={y=-32,x=76,z=-478},[_[1]]=true,[_[3]]={z=130,x=76,y=33.5},pos1={z=70,x=140,y=128.5},pos2={z=140,x=0,y=-0.5}},green={[_[2]]={y=-38,x=8,z=-541},[_[1]]=true,[_[3]]={z=67,x=8,y=27.5},pos1={z=0,x=0,y=-0.5},pos2={z=140,x=70,y=128.5}},blue={[_[2]]={y=-32,x=70,z=-601},[_[1]]=true,[_[3]]={z=7,x=70,y=33.5},pos1={z=0,x=140,y=-0.5},pos2={z=71,x=0,y=128.5}}}
chests = return {{amount=42,pos1={z=126,x=72,y=28.5},pos2={z=131,x=80,y=28.5}},{amount=42,pos1={z=74,x=128,y=32.5},pos2={z=82,x=133,y=32.5}},{amount=42,pos1={z=6,x=66,y=28.5},pos2={z=11,x=74,y=28.5}},{amount=42,pos1={z=63,x=7,y=22.5},pos2={z=71,x=12,y=22.5}}}
seasonal_end = 12.31
seasonal_start = 01.01
phys_jump = 1.2
phys_speed = 1
size = return {z=140,x=140,y=129}
map_version = 3
enabled = true
max_players = 32
name = Outer Space War
phys_gravity = 0.8
initial_stuff = return {"default:cobblestone 99"}
author = DarkWizard
hint = You can never have too many asteroids
license = CC-BY
others = 
treasures = 
skybox = none
enable_shadows = 0.26
min_players = 1
start_time = 4500
time_speed = 0
