game_modes = return {"potato"}
barrier_area = return {pos1={y=0,z=0,x=0},pos2={y=152,z=202,x=202}}
teams = local _={};_[1]="flag_pos";_[2]="enabled";return {red={pos1={y=152,z=101,x=101},[_[2]]=true,pos2={y=0,z=0,x=0},[_[1]]={y=11,z=26,x=26}},purple={pos1={y=152,z=101,x=101},[_[2]]=true,pos2={y=0,z=202,x=202},[_[1]]={y=11,z=176,x=176}},blue={pos1={y=152,z=101,x=101},[_[2]]=true,pos2={y=0,z=202,x=0},[_[1]]={y=11,z=176,x=26}},yellow={pos1={y=152,z=101,x=101},[_[2]]=true,pos2={y=0,z=0,x=202},[_[1]]={y=11,z=26,x=176}}}
chests = return {{pos1={y=0,z=101,x=0},amount=42,pos2={y=152,z=202,x=101}},{pos1={y=0,z=101,x=101},amount=42,pos2={y=152,z=202,x=202}},{pos1={y=0,z=0,x=101},amount=42,pos2={y=152,z=101,x=202}},{pos1={y=0,z=0,x=0},amount=42,pos2={y=152,z=101,x=101}}}
seasonal_end = 12.31
seasonal_start = 01.01
phys_jump = 1.2
phys_speed = 1.2
size = return {y=152,z=202,x=202}
map_version = 3
enabled = true
max_players = 32
name = Potato Volcano
phys_gravity = 0.9
initial_stuff = return {}
author = Themostrandom01
hint = 
license = CC BY-SA 4.0
others = 
treasures = 
skybox = none
enable_shadows = 0.26
min_players = 4
start_time = 5900
time_speed = 1
