game_modes = return {"potato"}
barrier_area = return {pos1={x=0,y=0,z=0},pos2={x=158,y=30,z=74}}
teams = local _={};_[1]="enabled";_[2]="flag_pos";return {red={[_[1]]=true,pos2={x=80,y=29,z=1},[_[2]]={x=153,y=14,z=69},pos1={x=157,y=1,z=73}},yellow={[_[1]]=true,pos2={x=1,y=1,z=73},[_[2]]={x=5,y=14,z=5},pos1={x=78,y=29,z=1}}}
chests = return {{pos1={x=1,y=1,z=1},amount=42,pos2={x=78,y=28,z=73}},{pos1={x=80,y=1,z=1},amount=42,pos2={x=157,y=28,z=73}}}
seasonal_end = 12.31
seasonal_start = 01.01
phys_jump = 1.2
phys_speed = 1.3
size = return {x=158,y=30,z=74}
map_version = 3
enabled = true
max_players = 32
name = Fry Grass Farm
phys_gravity = 1
initial_stuff = return {}
author = i35
hint = Have Fun!
license = CC-BY
others = Other info
treasures = 
skybox = none
enable_shadows = 0.26
min_players = 1
start_time = 5900
time_speed = 1
