game_modes = return {"classes","nade_fight","classic"}
barrier_area = return {pos2={z=99,x=99,y=91},pos1={z=0,x=0,y=0}}
teams = local _={};_[1]="look_pos";_[2]="flag_pos";_[3]="enabled";return {blue={[_[3]]=true,[_[2]]={z=3,x=96,y=51.5},pos2={z=48,x=53,y=90.5},[_[1]]={z=4,x=28671,y=5},pos1={z=0,x=99,y=-0.5}},yellow={[_[3]]=true,[_[2]]={z=96,x=3,y=51.5},pos2={z=50,x=52,y=90.5},[_[1]]={z=95,x=28580,y=5},pos1={z=99,x=0,y=-0.5}}}
chests = return {{amount=20,pos2={z=97,x=42,y=50.5},pos1={z=68,x=1,y=48.5}},{amount=20,pos2={z=31,x=98,y=50.5},pos1={z=2,x=57,y=48.5}}}
phys_jump = 1
phys_speed = 1.25
size = return {z=99,x=99,y=91}
map_version = 3
enabled = true
name = All Quiet on the Western Front
phys_gravity = 1
initial_stuff = return {"default:pick_steel","default:torch 20"}
author = w3kidsBoss
hint = The green waters are more than they seem
license = MIT
others = 
treasures = 
skybox = FullMoon
enable_shadows = 0
start_time = 0
time_speed = 0.25
