game_modes = return {"classes","nade_fight","classic"}
barrier_area = return {pos1={y=0,z=0,x=0},pos2={y=91,z=99,x=99}}
teams = local _={};_[1]="enabled";_[2]="look_pos";_[3]="flag_pos";return {yellow={[_[1]]=true,[_[2]]={y=5,z=95,x=28580},pos2={y=90.5,z=50,x=52},[_[3]]={y=51.5,z=96,x=3},pos1={y=-0.5,z=99,x=0}},blue={[_[1]]=true,[_[2]]={y=5,z=4,x=28671},pos2={y=90.5,z=48,x=53},[_[3]]={y=51.5,z=3,x=96},pos1={y=-0.5,z=0,x=99}}}
chests = return {{pos1={y=48.5,z=68,x=1},amount=20,pos2={y=50.5,z=97,x=42}},{pos1={y=48.5,z=2,x=57},amount=20,pos2={y=50.5,z=31,x=98}},{amount=20,pos1={y=50.5,z=1,x=1},pos2={y=52.5,z=49,x=53}},{amount=20,pos1={y=50.5,z=49,x=53},pos2={y=53.5,z=99,x=98}}}
phys_jump = 1
phys_speed = 0.85
size = return {y=91,z=99,x=99}
map_version = 3
enabled = true
name = All Quiet on the Western Front
phys_gravity = 1
initial_stuff = return {"default:pick_steel","default:torch 20","ctf_ranged:pistol_loaded","ctf_ranged:ammo 3"}
author = w3kidsBoss
hint = The green waters are more than they seem
license = MIT
others = 
treasures =
skybox = FullMoon
enable_shadows = 0
start_time = 0
time_speed = 0.01
seasonal_end = 12.31
seasonal_start = 01.01
max_players = 8
min_players = 2

